title: Rețete
author: MihneaM
email: mihnea@mihaim.ro
description: > # this means to ignore newlines until "baseurl:"
  Rețete pentru oameni organizați.
# social links
github_username:  mihnea-mihai # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme:
  minima:
    skin: dark
