title: Rețete și atât
author: MihneaM
email: mihnea@mihaim.ro
description: Rețete fără aditivi pentru oameni organizați.

github_username:  mihnea-mihai

show_excerpts: false

theme: jekyll-theme-cayman
